services:
  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=Europe/Zagreb
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      - /home/kmarsic/config:/app/config
    restart: always
