services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    user: "1000"
    ports:
     - '3010:3000'
    volumes:
      - /home/kmarsic/grafana/data:/var/lib/grafana
