services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: always
    user: "1000"
    ports:
     - '3010:3000'
    volumes:
      - /home/kmarsic/grafana/data:/var/lib/grafana
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: /home/kmarsic/volume_backup/backup.env
    volumes:
      - ./data:/backup/data:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - grafana_backup:/archive
volumes:
  grafana_backup:
    external: true
