services:
  app:
    image: jc21/nginx-proxy-manager:latest
    restart: always
    labels:
      wud.trigger.include: discord.discord,dockercompose.nginx
    ports:
      - 80:80
      - 443:443
      - 81:81
    environment:
      DB_MYSQL_HOST: db
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: npm
      DB_MYSQL_PASSWORD: npm
      DB_MYSQL_NAME: npm
    volumes:
      - ./data:/data
      - ./letsencrypt:/etc/letsencrypt
    depends_on:
      - db
  db:
    image: jc21/mariadb-aria:latest
    restart: always
    labels:
      wud.trigger.include: discord.discord
    environment:
      MYSQL_ROOT_PASSWORD: npm
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: npm
    volumes:
      - ./mysql:/var/lib/mysql
networks: {}
