---
services:
  calibre-web-automated:
    image: crocodilestick/calibre-web-automated:latest
    container_name: calibre-web-automated
    environment:
      - TZ=Europe/Belgrade
    volumes:
      - ./config/folder:/config 
      # This is an ingest dir. Anything added here will be automatically added to your library according to the settings you have configured in CWA Settings page. All files placed here are REMOVED AFTER PROCESSING
      - /mnt/media/books:/cwa-book-ingest
      # If you don't have an existing library, CWA will automatically create one at the bind provided here
      - ./library:/calibre-library 
    ports:
      - 8083:8083 
    restart: unless-stopped