services:
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wiki
      POSTGRES_PASSWORD: wikijsrocks
      POSTGRES_USER: wikijs
    logging:
      driver: "none"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
    labels:
      - docker-volume-backup.stop-during-backup=true
  wiki:
    image: ghcr.io/requarks/wiki:2
    depends_on:
      - db
    environment:
      DB_TYPE: postgres
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: wikijs
      DB_PASS: wikijsrocks
      DB_NAME: wiki
    restart: always
    ports:
      - "8020:3000"
    volumes:
      - /home/kmarsic/wikijs/data:/wiki/data/content
      - /home/kmarsic/wikijs/ssh:/wiki/data/ssh
  backup:
    image: offen/docker-volume-backup:latest
    restart: always
    env_file: /home/kmarsic/volume_backup/backup.env
    volumes:
      - db-data:/backup/wiki-db-backup:ro
      - /home/kmarsic/wikijs/data:/backup/wiki-app-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - wikijs_backup:/archive

volumes:
  db-data:
  wikijs_backup:
    external: true
